### PR TITLE
hypercorn 0.17.3 (noarch, outputs, add maintainer)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- [x] blocked by https://github.com/conda-forge/staged-recipes/pull/26581
- [x] blocked by https://github.com/conda-forge/staged-recipes/pull/26617
  -  [x] blocked by https://github.com/conda-forge/service_identity-feedstock/pull/6

Changes:
- [x] make `noarch`
- [x] move `[extras]` to outputs (with `run_constrained` in main)
- [x] run tests against `all` package 
- [x] update the project metadata   
 - [x] add maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/hypercorn ready for review :corn:

**Comment by dhirschfeld** [comment]
It all looks pretty good to me - thanks @bollwyvl!

Only one question. The `hypercorn-with-*` naming convention seems slightly cumbersome, what do you think about ommittig the `-with`?
```
hypercorn
hypercorn-trio
hypercorn-uvloop
hypercorn-h3
hypercorn-all
```

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by synapticarbors** [comment]
Are there other examples of feedstocks having different outputs for extras? In the past I've feel like we've largely ignored it.

**Comment by bollwyvl** [comment]
I'll certainly agree that `[extra]`s are mostly a pain (`pip` itself doesn't handle them well). However, when trying to keep a deep web stack working properly, it becomes a bigger issue when downstreams start depending on them, and the pins are not inconsequential (e.g. have hard API epoch boundaries).

Some web-adjacent things with multiple outputs:
- [uvicorn](https://github.com/conda-forge/uvicorn-feedstock/blob/main/recipe/meta.yaml)
- [starlette](https://github.com/conda-forge/starlette-feedstock/blob/main/recipe/meta.yaml)
- [strawberry-graphql](https://github.com/conda-forge/strawberry-graphql-feedstock/blob/main/recipe/meta.yaml#L27)
- [litestar](https://github.com/conda-forge/litestar-feedstock/blob/main/recipe/meta.yaml#L26)
- [gql](https://github.com/conda-forge/gql-feedstock/blob/beta/recipe/meta.yaml#L26)
- [jsonschema](https://github.com/conda-forge/jsonschema-feedstock/blob/main/recipe/meta.yaml)

**Comment by synapticarbors** [comment]
@bollwyvl -- Thanks for the references. It looks like litestar uses the `-with-` convention, and others don't. I think I'd prefer not using `-with-`. 

@dhirschfeld and I are maintainers on `fastapi` and I feel like we should probably move to this sort of convention. We've been ignoring it along with the `fastapi-slim` build since 0.111.0 https://github.com/conda-forge/fastapi-feedstock/pull/127#issuecomment-2093869696

**Review by dhirschfeld — APPROVED** [review]
LGTM! :shipit:

**Comment by bollwyvl** [comment]
Oof, yeah, the `typer-slim` thing hit at the same time as `fastapi-slim`... indeed, ended up with this special-magic-env-var [script](https://github.com/conda-forge/typer-feedstock/blob/main/recipe/build_typer.py) which lets `typer` appease `pip chcek`, by depending on `typer-slim` without clobbering files.

As a `fastapi` conusmer, I can have a look at proposing an adaptation of that over there...

**Comment by synapticarbors** [comment]
At least for `fastapi-slim`, it looks like it is being deprecated as just a mirror of `fastapi` as of this comment from two weeks ago: https://github.com/fastapi/fastapi/discussions/11525#discussioncomment-10224030

It looks like `fastapi` alone will be the "slim" and then there will be the `standard` and `all` packages.

**Comment by bollwyvl** [comment]
Ah, well, i'll let sleeping `fastapi`s lie, then!

**Comment by dhirschfeld** [comment]
> I think I'd prefer not using `-with-`.

@bollwyvl has addressed this feedback so this should be good to merge?

**Pull request merged**
